apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radio-room
  namespace: radio-room
  annotations:
    nginx.ingress.kubernetes.io/websocket-services: "radio-room"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: radio-room.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radio-room
                port:
                  number: 3000
